import { gql } from '@apollo/client/index.js';
import { 
  SEARCH_FULL as SEARCH_QUERY,
  ADVANCED_SEARCH as ADVANCED_SEARCH_QUERY,
  GET_COURSES_FULL as GET_COURSES_QUERY,
  GET_COURSE as GET_COURSE_QUERY,
  GET_DISCORD_SERVERS as GET_DISCORD_SERVERS_QUERY,
  GET_DISCORD_SERVER as GET_DISCORD_SERVER_QUERY,
  GET_REDDIT_COMMUNITIES as GET_REDDIT_COMMUNITIES_QUERY,
  GET_REDDIT_COMMUNITY as GET_REDDIT_COMMUNITY_QUERY,
  GET_WGU_CONNECT_GROUPS as GET_WGU_CONNECT_GROUPS_QUERY,
  GET_WGU_CONNECT_GROUP as GET_WGU_CONNECT_GROUP_QUERY,
  GET_DEGREE_PLANS_FULL as GET_DEGREE_PLANS_QUERY,
  GET_DEGREE_PLAN as GET_DEGREE_PLAN_QUERY,
  GET_STUDENT_GROUPS as GET_STUDENT_GROUPS_QUERY,
  GET_STUDENT_GROUP as GET_STUDENT_GROUP_QUERY
} from '../../../functions/src/graphql/queries';

// Wrap imported queries with gql tag for Apollo Client
export const SEARCH = gql`${SEARCH_QUERY}`;

export const ADVANCED_SEARCH = gql`${ADVANCED_SEARCH_QUERY}`;

export const GET_COURSES = gql`${GET_COURSES_QUERY}`;

export const GET_COURSE = gql`${GET_COURSE_QUERY}`;

export const GET_DISCORD_SERVERS = gql`${GET_DISCORD_SERVERS_QUERY}`;

export const GET_DISCORD_SERVER = gql`${GET_DISCORD_SERVER_QUERY}`;

export const GET_REDDIT_COMMUNITIES = gql`${GET_REDDIT_COMMUNITIES_QUERY}`;

export const GET_REDDIT_COMMUNITY = gql`${GET_REDDIT_COMMUNITY_QUERY}`;

export const GET_WGU_CONNECT_GROUPS = gql`${GET_WGU_CONNECT_GROUPS_QUERY}`;

export const GET_WGU_CONNECT_GROUP = gql`${GET_WGU_CONNECT_GROUP_QUERY}`;

export const GET_DEGREE_PLANS = gql`${GET_DEGREE_PLANS_QUERY}`;

export const GET_DEGREE_PLAN = gql`${GET_DEGREE_PLAN_QUERY}`;

export const GET_STUDENT_GROUPS = gql`${GET_STUDENT_GROUPS_QUERY}`;

export const GET_STUDENT_GROUP = gql`${GET_STUDENT_GROUP_QUERY}`;