name: PR Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to checkout the code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.0.0 # Pin to a specific version for reproducibility

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Compile check
        run: bun run compile

      - name: Build extension
        run: bun run build
